refresh:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: zeekr_ev

dump_raw_status:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: zeekr_ev
    vin:
      required: false
      example: "LXXXA1SXXXN022XXX"
      selector:
        text:
